-- Sample data for Users
INSERT INTO users (name, email, phone, username, password, membership_type, active)
VALUES
    ('John Doe', 'john@example.com', '123-456-7890', 'johndoe', 'password123', 'PREMIUM', true),
    ('Jane Smith', 'jane@example.com', '555-123-4567', 'janesmith', 'password456', 'BASIC', true),
    ('Mike Johnson', 'mike@example.com', '888-777-6666', 'mikej', 'password789', 'VIP', true),
    ('Sarah Williams', 'sarah@example.com', '444-333-2222', 'sarahw', 'password321', 'PREMIUM', true),
    ('David Brown', 'david@example.com', '111-222-3333', 'davidb', 'password654', 'BASIC', false);

-- Sample data for Books
INSERT INTO books (title, author, isbn, publication_date, description, genre, total_copies, available_copies)
VALUES
    ('The Great Gatsby', 'F. Scott Fitzgerald', '9780743273565', '1925-04-10', 'A novel about the American Dream and its corruption in the 1920s.', 'Classic', 5, 5),
    ('To Kill a Mockingbird', 'Harper Lee', '9780061120084', '1960-07-11', 'A novel about racial injustice and moral growth in the American South.', 'Classic', 3, 3),
    ('1984', 'George Orwell', '9780451524935', '1949-06-08', 'A dystopian novel about totalitarianism and surveillance.', 'Science Fiction', 4, 4),
    ('Pride and Prejudice', 'Jane Austen', '9780141439518', '1813-01-28', 'A romantic novel of manners in early 19th-century England.', 'Romance', 2, 2),
    ('The Hobbit', 'J.R.R. Tolkien', '9780547928227', '1937-09-21', 'A fantasy novel about the adventures of Bilbo Baggins.', 'Fantasy', 6, 6),
    ('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', '9780590353427', '1997-06-26', 'The first book in the Harry Potter series.', 'Fantasy', 8, 8),
    ('The Catcher in the Rye', 'J.D. Salinger', '9780316769488', '1951-07-16', 'A novel about teenage alienation and identity.', 'Coming of Age', 3, 3),
    ('The Lord of the Rings', 'J.R.R. Tolkien', '9780618640157', '1954-07-29', 'An epic high-fantasy trilogy.', 'Fantasy', 4, 4),
    ('Brave New World', 'Aldous Huxley', '9780060850524', '1932-01-01', 'A dystopian novel about a genetically engineered future society.', 'Science Fiction', 3, 3),
    ('The Alchemist', 'Paulo Coelho', '9780061122415', '1988-01-01', 'A philosophical novel about following your dreams.', 'Fiction', 5, 5);

-- Sample data for Loans (create some active loans)
-- First, we need the user and book IDs, which will be generated by the database
-- Let's assume user IDs 1-3 and book IDs 1-3 for these examples

-- John borrows The Great Gatsby
INSERT INTO loans (user_id, book_id, loan_date, due_date, status)
VALUES (1, 1, CURRENT_DATE - 7, CURRENT_DATE + 7, 'BORROWED');

-- Update available copies for The Great Gatsby
UPDATE books SET available_copies = available_copies - 1 WHERE id = 1;

-- Jane borrows To Kill a Mockingbird
INSERT INTO loans (user_id, book_id, loan_date, due_date, status)
VALUES (2, 2, CURRENT_DATE - 10, CURRENT_DATE + 4, 'BORROWED');

-- Update available copies for To Kill a Mockingbird
UPDATE books SET available_copies = available_copies - 1 WHERE id = 2;

-- Mike borrows 1984
INSERT INTO loans (user_id, book_id, loan_date, due_date, status)
VALUES (3, 3, CURRENT_DATE - 14, CURRENT_DATE - 1, 'BORROWED');

-- Update available copies for 1984
UPDATE books SET available_copies = available_copies - 1 WHERE id = 3;

-- Add one overdue loan
INSERT INTO loans (user_id, book_id, loan_date, due_date, status)
VALUES (1, 4, CURRENT_DATE - 30, CURRENT_DATE - 15, 'BORROWED');

-- Update available copies for Pride and Prejudice
UPDATE books SET available_copies = available_copies - 1 WHERE id = 4;

-- Add one returned book
INSERT INTO loans (user_id, book_id, loan_date, due_date, return_date, status)
VALUES (2, 5, CURRENT_DATE - 20, CURRENT_DATE - 6, CURRENT_DATE - 8, 'RETURNED');